 local menue0e4fc6213e8b3593495a7260c3a4c2e = {
     {"Accerciser", "/usr/bin/accerciser", "/usr/share/icons/hicolor/16x16/apps/accerciser.png" },
     {"Screen Reader", "orca --replace", "/usr/share/icons/hicolor/16x16/apps/orca.png" },
 }

 local menu98edb85b00d9527ad5acebe451b3fae6 = {
     {"7-Zip FM", "7zFM", "/usr/share/icons/hicolor/32x32/apps/p7zip.png" },
     {"Akonaditray", "akonaditray", "/usr/share/icons/hicolor/22x22/apps/akonaditray.png" },
     {"Archive Manager", "file-roller ", "/usr/share/icons/hicolor/16x16/apps/file-roller.png" },
     {"AutoKey", "autokey-gtk -c"},
     {"AutoKey (KDE)", "autokey-qt"},
     {"Calculator", "gnome-calculator", "/usr/share/icons/gnome/16x16/apps/accessories-calculator.png" },
     {"Character Map", "gucharmap", "/usr/share/icons/gnome/16x16/apps/accessories-character-map.png" },
     {"Clocks", "gnome-clocks", "/usr/share/icons/hicolor/16x16/apps/gnome-clocks.png" },
     {"Desktop Search", "tracker-needle", "/usr/share/icons/gnome/16x16/actions/system-search.png" },
     {"Disks", "gnome-disks", "/usr/share/icons/hicolor/16x16/apps/gnome-disks.png" },
     {"Engrampa Archive Manager", "engrampa ", "/usr/share/icons/hicolor/16x16/apps/engrampa.png" },
     {"Fern Wifi Cracker", "gksu fern-wifi-cracker", "///usr/share/fern-wifi-cracker/resources/screen_splash.png" },
     {"Files", "nautilus --new-window ", "/usr/share/icons/gnome/16x16/apps/system-file-manager.png" },
     {"Font Viewer", "gnome-font-viewer ", "/usr/share/icons/gnome/16x16/apps/preferences-desktop-font.png" },
     {"Galculator", "galculator", "/usr/share/icons/hicolor/48x48/apps/galculator.png" },
     {"Growl For Linux", "/usr/bin/gol", "///usr/share/growl-for-linux/data/icon.png" },
     {"HP Device Manager", "hp-toolbox", "///usr/share/hplip/data/images/128x128/hp_logo.png" },
     {"Hwacha", "/opt/hwacha/hwacha", "///opt/hwacha/hwacha.png" },
     {"IPython Qt console", "ipython qtconsole", "/usr/share/icons/gnome/16x16/status/gnome-netstatus-idle.png" },
     {"IPython2 Qt console", "ipython2 qtconsole", "/usr/share/icons/gnome/16x16/status/gnome-netstatus-idle.png" },
     {"Johnny", "johnny", "/usr/share/pixmaps/johnny.png" },
     {"KeePassX", "keepassx ", "/usr/share/pixmaps/keepassx.xpm" },
     {"Maps", "gnome-maps", "/usr/share/icons/hicolor/16x16/apps/gnome-maps.png" },
     {"Metasploit AV Evasion", "xterm -e metasploitavevasion", "/usr/share/pixmaps/metasploitavevasion.png" },
     {"Nemo", "nemo ", "/usr/share/icons/gnome/16x16/places/folder.png" },
     {"Notes", "bijiben ", "/usr/share/icons/hicolor/16x16/apps/bijiben.png" },
     {"PCManFM File Manager", "pcmanfm-qt ", "/usr/share/icons/gnome/16x16/apps/system-file-manager.png" },
     {"PacmanXG", "ssx pacmanxg"},
     {"Passwords and Keys", "/usr/bin/seahorse", "/usr/share/icons/hicolor/16x16/apps/seahorse.png" },
     {"Pip3line", "pip3line", "///usr/share/icons/hicolor/128x128/apps/pip3line.png" },
     {"Pluma", "pluma ", "/usr/share/icons/gnome/16x16/apps/accessories-text-editor.png" },
     {"RFDump", "rfdump", "///usr/share/pixmaps/rfdump.png" },
     {"Random Wordlist Generator", "randomwordlistgenerator", "///usr/share/pixmaps/randomwordlistgenerator.png" },
     {"Recoll", "recoll", "/usr/share/icons/hicolor/48x48/apps/recoll.png" },
     {"Root Terminal", "gksu -l gnome-terminal", "/usr/share/pixmaps/gksu-root-terminal.png" },
     {"Screen Reader", "orca --replace", "/usr/share/icons/hicolor/16x16/apps/orca.png" },
     {"Screenshot", "gnome-screenshot --interactive", "/usr/share/icons/gnome/16x16/apps/applets-screenshooter.png" },
     {"Synapse", "synapse"},
     {"Tomboy Notes", "tomboy --search", "/usr/share/icons/hicolor/16x16/apps/tomboy.png" },
     {"Weather", "gapplication launch org.gnome.Weather.Application", "/usr/share/icons/hicolor/16x16/apps/org.gnome.Weather.Application.png" },
     {"Zim Desktop Wiki", "zim", "/usr/share/pixmaps/zim.png" },
     {"gedit", "gedit ", "/usr/share/icons/gnome/16x16/apps/accessories-text-editor.png" },
     {"ipython", "xterm -e ipython", "/usr/share/icons/gnome/16x16/status/gnome-netstatus-idle.png" },
     {"ipython2", "xterm -e ipython2", "/usr/share/icons/gnome/16x16/status/gnome-netstatus-idle.png" },
     {"ownCloud desktop sync client ", "owncloud", "/usr/share/icons/hicolor/22x22/apps/owncloud.png" },
     {"x3270", "/usr/bin/x3270", "///usr/share/pixmaps/x3270-icon2.xpm" },
 }

 local menude7a22a0c94aa64ba2449e520aa20c99 = {
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
 }

 local menu251bd8143891238ecedc306508e29017 = {
     {"AisleRiot Solitaire", "sol", "/usr/share/icons/hicolor/16x16/apps/gnome-aisleriot.png" },
     {"Chess", "gnome-chess", "/usr/share/icons/hicolor/16x16/apps/gnome-chess.png" },
     {"Dosbox", "dosbox", "/usr/share/pixmaps/dosbox.png" },
     {"Dwarf Fortress", "dwarffortress", "///usr/share/pixmaps/dwarffortress.png" },
     {"Feed The Beast", "feedthebeast", "/usr/share/icons/hicolor/16x16/apps/feedthebeast.png" },
     {"Firestorm Second Life viewer", "/usr/bin/firestorm", "///usr/share/pixmaps/firestorm_icon.png" },
     {"Five or More", "five-or-more", "/usr/share/icons/hicolor/16x16/apps/five-or-more.png" },
     {"Four-in-a-row", "four-in-a-row", "/usr/share/icons/hicolor/16x16/apps/four-in-a-row.png" },
     {"Game Conqueror", "gameconqueror", "/usr/share/pixmaps/GameConqueror_128x128.png" },
     {"Hitori", "hitori", "/usr/share/icons/hicolor/16x16/apps/hitori.png" },
     {"Iagno", "iagno", "/usr/share/icons/hicolor/16x16/apps/iagno.png" },
     {"Klotski", "gnome-klotski", "/usr/share/icons/hicolor/16x16/apps/gnome-klotski.png" },
     {"Lights Off", "lightsoff"},
     {"Mahjongg", "gnome-mahjongg", "/usr/share/icons/hicolor/16x16/apps/gnome-mahjongg.png" },
     {"Mari0", "mari0"},
     {"Minecraft", "minecraft", "///usr/share/pixmaps/minecraft.png" },
     {"Mines", "gnome-mines", "/usr/share/icons/hicolor/16x16/apps/gnome-mines.png" },
     {"Minetest", "minetest"},
     {"Nibbles", "gnome-nibbles", "/usr/share/icons/hicolor/16x16/apps/gnome-nibbles.png" },
     {"PlayOnLinux", "playonlinux", "///usr/share/playonlinux/etc/playonlinux.png" },
     {"Quadrapassel", "quadrapassel", "/usr/share/icons/hicolor/16x16/apps/quadrapassel.png" },
     {"Robots", "gnome-robots", "/usr/share/icons/hicolor/16x16/apps/gnome-robots.png" },
     {"RuneScape", "/opt/runescape/runescape", "///opt/runescape/share/img/runescape.png" },
     {"RuneScape OldSchool", "/opt/runescape/runescape --prmfile=oldschool.prm", "///opt/runescape/share/img/runescape.png" },
     {"Runescape Client Updater", "xterm -e /opt/runescape/rsu/rsu-query rsu.download.client", "///opt/runescape/share/img/update-runescape.png" },
     {"StarMade", "starmade", "///usr/share/pixmaps/starmade.png" },
     {"Steam", "env STEAM_FRAME_FORCE_CLOSE=1 /usr/bin/steam ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Steam", "/usr/bin/steam ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Sudoku", "gnome-sudoku", "/usr/share/icons/hicolor/16x16/apps/gnome-sudoku.png" },
     {"SuperTux 2", "supertux2", "/usr/share/pixmaps/supertux.png" },
     {"Swell Foop", "swell-foop", "/usr/share/icons/hicolor/16x16/apps/swell-foop.png" },
     {"Tali", "tali", "/usr/share/icons/hicolor/16x16/apps/tali.png" },
     {"Tetravex", "gnome-tetravex", "/usr/share/icons/hicolor/16x16/apps/gnome-tetravex.png" },
     {"Xonotic (GLX)", "/usr/bin/xonotic-glx", "/usr/share/icons/hicolor/16x16/apps/xonotic.png" },
     {"Xonotic (SDL)", "/usr/bin/xonotic-sdl", "/usr/share/icons/hicolor/16x16/apps/xonotic.png" },
 }

 local menud334dfcea59127bedfcdbe0a3ee7f494 = {
     {"Document Viewer", "evince ", "/usr/share/icons/hicolor/16x16/apps/evince.png" },
     {"Eye of MATE Image Viewer", "eom ", "/usr/share/icons/hicolor/16x16/apps/eom.png" },
     {"FontForge", "fontforge ", "/usr/share/icons/hicolor/16x16/apps/fontforge.png" },
     {"GNU Image Manipulation Program", "gimp-2.8 ", "/usr/share/icons/hicolor/16x16/apps/gimp.png" },
     {"Image Viewer", "eog ", "/usr/share/icons/hicolor/16x16/apps/eog.png" },
     {"Image Viewer", "gpicview ", "/usr/share/icons/hicolor/48x48/apps/gpicview.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"ScreenCloud", "/opt/screencloud/screencloud.sh", "/usr/share/icons/hicolor/16x16/apps/screencloud.png" },
     {"xgps", "xgps", "///usr/share/gpsd/gpsd-logo.png" },
     {"xgpsspeed", "xgpsspeed", "///usr/share/gpsd/gpsd-logo.png" },
 }

 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"Amap", "amap"},
     {"Angry IP Scanner", "ipscan"},
     {"Avahi SSH Server Browser", "/usr/bin/bssh", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Avahi VNC Server Browser", "/usr/bin/bvnc", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Browse Mirrored Websites", "webhttrack browse", "/usr/share/icons/hicolor/16x16/apps/httrack.png" },
     {"Caja Dropbox", "caja-dropbox start -i", "/usr/share/icons/hicolor/16x16/apps/caja-dropbox.png" },
     {"Chromium", "chromium ", "/usr/share/icons/hicolor/16x16/apps/chromium.png" },
     {"Dell SonicWALL NetExtender", "/usr/bin/netExtenderGui", "///usr/share/netExtender/icons/nx48.xpm" },
     {"ELinks", "xterm -e /usr/bin/elinks ", "/usr/share/icons/gnome/16x16/mimetypes/html.png" },
     {"Empathy", "empathy", "/usr/share/icons/hicolor/16x16/apps/empathy.png" },
     {"EtherApe", "etherape", "/usr/share/pixmaps/etherape.png" },
     {"Ettercap", "ettercap-pkexec -G", "/usr/share/pixmaps/ettercap.svg" },
     {"FileZilla", "filezilla", "/usr/share/icons/hicolor/16x16/apps/filezilla.png" },
     {"Firefox", "/usr/lib/firefox/firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox.png" },
     {"Firefox Developer", "firefox-developer ", "/usr/share/pixmaps/firefox-developer-icon.png" },
     {"Gajim", "gajim", "/usr/share/icons/hicolor/64x64/apps/gajim.png" },
     {"Gnome-RDP", "gnome-rdp", "/usr/share/pixmaps/gnome-rdp.png" },
     {"Google Chrome", "/usr/bin/google-chrome-stable ", "/usr/share/icons/hicolor/16x16/apps/google-chrome.png" },
     {"Google Chrome (beta)", "/usr/bin/google-chrome-beta ", "/usr/share/icons/hicolor/16x16/apps/google-chrome-beta.png" },
     {"Google Chrome (unstable)", "/usr/bin/google-chrome-unstable ", "/usr/share/icons/hicolor/16x16/apps/google-chrome-unstable.png" },
     {"KRDC", "krdc -caption KRDC "},
     {"KompoZer", "kompozer", "/usr/share/pixmaps/kompozer.png" },
     {"Midori", "midori ", "/usr/share/icons/hicolor/16x16/apps/midori.png" },
     {"Midori Private Browsing", "midori --private ", "/usr/share/icons/hicolor/16x16/apps/midori.png" },
     {"Mumble", "mumble"},
     {"Net Activity Viewer", "netactview", "/usr/share/pixmaps/netactview.png" },
     {"Netsurf", "netsurf ", "/usr/share/pixmaps/netsurf.png" },
     {"OnionShare", "/usr/bin/onionshare-gui", "///usr/share/pixmaps/onionshare80.xpm" },
     {"Opera", "opera ", "/usr/share/icons/hicolor/16x16/apps/opera.png" },
     {"Pidgin Internet Messenger", "pidgin", "/usr/share/icons/hicolor/16x16/apps/pidgin.png" },
     {"Polari", "polari", "/usr/share/icons/hicolor/16x16/apps/polari.png" },
     {"Quassel IRC (Client only)", "quasselclient", "/usr/share/icons/hicolor/16x16/apps/quassel.png" },
     {"Remmina", "remmina", "/usr/share/icons/hicolor/16x16/apps/remmina.png" },
     {"Remote Desktop Viewer", "vinagre ", "/usr/share/icons/gnome/16x16/apps/preferences-desktop-remote-desktop.png" },
     {"SeaMonkey internet suite", "seamonkey", "/usr/share/pixmaps/seamonkey.png" },
     {"Skype", "skype ", "/usr/share/icons/hicolor/16x16/apps/skype.png" },
     {"Steam", "env STEAM_FRAME_FORCE_CLOSE=1 /usr/bin/steam ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Steam", "/usr/bin/steam ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"TeamSpeak 3", "teamspeak3", "/usr/share/pixmaps/teamspeak3.xpm" },
     {"TeamViewer 10", "/opt/teamviewer/tv_bin/script/teamviewer", "///opt/teamviewer/tv_bin/desktop/teamviewer.png" },
     {"Thunderbird", "thunderbird ", "/usr/share/icons/hicolor/16x16/apps/thunderbird.png" },
     {"TigerVNC Viewer", "/usr/bin/vncviewer", "/usr/share/icons/hicolor/16x16/apps/tigervnc.png" },
     {"Transmission", "transmission-gtk ", "/usr/share/icons/hicolor/16x16/apps/transmission.png" },
     {"UltraVNC Viewer", "ultravnc-viewer", "/usr/share/icons/hicolor/16x16/apps/ultravnc-viewer.png" },
     {"UltraVNC Viewer Listen mode", "ultravnc-viewer -listen", "/usr/share/icons/hicolor/16x16/apps/ultravnc-viewer.png" },
     {"Vivaldi", "/usr/bin/vivaldi-preview ", "/usr/share/icons/hicolor/16x16/apps/vivaldi.png" },
     {"Wavemon", "wavemon"},
     {"Web", "epiphany ", "/usr/share/icons/gnome/16x16/apps/web-browser.png" },
     {"WebHTTrack Website Copier", "webhttrack", "/usr/share/icons/hicolor/16x16/apps/httrack.png" },
     {"XSSer", "/usr/bin/xsser --gtk --silent", "///usr/share/xsser/gtk/images/xssericon_24x24.png" },
     {"Zenmap", "zenmap ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"Zenmap (as root)", "/usr/share/zenmap/su-to-zenmap.sh ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"tcpjunk", "tcpjunk -x", "/usr/share/pixmaps/tcpjunk.png" },
     {"w3af", "w3af-gui", "///usr/share/w3af/doc/sphinx/images/w3af-logo.png" },
 }

 local menudf814135652a5a308fea15bff37ea284 = {
     {"Atril Document Viewer", "atril ", "/usr/share/icons/hicolor/16x16/apps/atril.png" },
     {"Dictionary", "gnome-dictionary", "/usr/share/icons/gnome/16x16/apps/accessories-dictionary.png" },
     {"Document Viewer", "evince ", "/usr/share/icons/hicolor/16x16/apps/evince.png" },
     {"Evolution", "evolution ", "/usr/share/icons/hicolor/16x16/apps/evolution.png" },
     {"LibreOffice", "libreoffice ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Installer", "libreoffice-installer", "/usr/share/icons/gnome/16x16/actions/document-save.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"Wordview Microsoft doc Viewer", "wordview", "/usr/share/pixmaps/wordview.xpm" },
 }

 local menu6311ae17c1ee52b36e68aaf4ad066387 = {
     {"Admsnmp", "admsnmp"},
     {"Argtable", "argtable"},
     {"Cuckoo", "/usr/bin/cuckoo"},
     {"ut2004", "/usr/local/games/ut2004//ut2004", "///usr/local/games/ut2004//ut2004.xpm" },
 }

 local menue6f43c40ab1c07cd29e4e83e4ef6bf85 = {
     {"Accerciser", "/usr/bin/accerciser", "/usr/share/icons/hicolor/16x16/apps/accerciser.png" },
     {"Anjuta", "anjuta ", "/usr/share/icons/hicolor/16x16/apps/anjuta.png" },
     {"Arduino", "arduino ", "/usr/share/icons/hicolor/256x256/apps/arduino.png" },
     {"Brackets", "/opt/brackets/brackets ", "/usr/share/icons/hicolor/32x32/apps/brackets.png" },
     {"CMake", "cmake-gui ", "/usr/share/icons/hicolor/32x32/apps/CMakeSetup.png" },
     {"Database browser", "gda-browser-5.0", "/usr/share/pixmaps/gda-browser-5.0.png" },
     {"Devhelp", "devhelp", "/usr/share/icons/hicolor/16x16/apps/devhelp.png" },
     {"Dissy", "dissy", "/usr/share/pixmaps/dissy.svg" },
     {"Emacs", "emacs ", "/usr/share/icons/hicolor/16x16/apps/emacs.png" },
     {"Evan's Debugger", "edb"},
     {"FLUID", "fluid ", "/usr/share/icons/hicolor/16x16/apps/fluid.png" },
     {"Glade", "glade ", "/usr/share/icons/hicolor/16x16/apps/glade.png" },
     {"IPython Qt console", "ipython qtconsole", "/usr/share/icons/gnome/16x16/status/gnome-netstatus-idle.png" },
     {"IPython2 Qt console", "ipython2 qtconsole", "/usr/share/icons/gnome/16x16/status/gnome-netstatus-idle.png" },
     {"KompoZer", "kompozer", "/usr/share/pixmaps/kompozer.png" },
     {"NetBeans", "netbeans", "/usr/share/pixmaps/netbeans.png" },
     {"OpenJDK Monitoring & Management Console", "/usr/bin/jconsole", "/usr/share/icons/hicolor/16x16/apps/java.png" },
     {"OpenJDK Policy Tool", "/usr/bin/policytool", "/usr/share/icons/hicolor/16x16/apps/java.png" },
     {"Qt Assistant", "/usr/lib/qt/bin/assistant", "/usr/share/icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Designer", "/usr/lib/qt/bin/designer", "/usr/share/icons/hicolor/128x128/apps/QtProject-designer.png" },
     {"Qt Linguist", "/usr/lib/qt/bin/linguist", "/usr/share/icons/hicolor/16x16/apps/linguist.png" },
     {"Qt QDbusViewer ", "/usr/lib/qt/bin/qdbusviewer", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer.png" },
     {"Qt4 Assistant ", "assistant-qt4", "/usr/share/icons/hicolor/32x32/apps/assistant-qt4.png" },
     {"Qt4 Designer", "designer-qt4", "/usr/share/icons/hicolor/128x128/apps/designer-qt4.png" },
     {"Qt4 Linguist ", "linguist-qt4", "/usr/share/icons/hicolor/16x16/apps/linguist-qt4.png" },
     {"Qt4 QDbusViewer ", "qdbusviewer-qt4", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer-qt4.png" },
     {"Sublime Text 3 Dev", "subl3 ", "/usr/share/icons/hicolor/16x16/apps/sublime-text.png" },
     {"VisualVM", "/usr/bin/visualvm", "///usr/share/visualvm/icon.png" },
     {"gitg", "gitg --no-wd ", "/usr/share/icons/hicolor/16x16/apps/gitg.png" },
     {"haroopad", "haroopad ", "/usr/share/icons/hicolor/16x16/apps/haroopad.png" },
     {"ipython", "xterm -e ipython", "/usr/share/icons/gnome/16x16/status/gnome-netstatus-idle.png" },
     {"ipython2", "xterm -e ipython2", "/usr/share/icons/gnome/16x16/status/gnome-netstatus-idle.png" },
 }

 local menu52dd1c847264a75f400961bfb4d1c849 = {
     {"Audacious", "audacious ", "/usr/share/icons/hicolor/48x48/apps/audacious.png" },
     {"Brasero", "brasero ", "/usr/share/icons/hicolor/16x16/apps/brasero.png" },
     {"Cheese", "cheese", "/usr/share/icons/hicolor/16x16/apps/cheese.png" },
     {"Clementine", "clementine ", "/usr/share/icons/hicolor/64x64/apps/application-x-clementine.png" },
     {"Feed The Beast", "feedthebeast", "/usr/share/icons/hicolor/16x16/apps/feedthebeast.png" },
     {"LXMusic simple music player", "lxmusic", "/usr/share/pixmaps/lxmusic.png" },
     {"Music", "gnome-music", "/usr/share/icons/hicolor/16x16/apps/gnome-music.png" },
     {"Pithos", "pithos"},
     {"Plex Home Theater", "/usr/bin/plexhometheater.sh", "///usr/share/pixmaps/plexhometheater.png" },
     {"PulseAudio Volume Control", "pavucontrol", "/usr/share/icons/hicolor/16x16/apps/multimedia-volume-control.png" },
     {"Qt V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"Spotify", "spotify ", "/usr/share/icons/hicolor/16x16/apps/spotify-client.png" },
     {"VLC media player", "/usr/bin/vlc --started-from-file ", "/usr/share/icons/hicolor/16x16/apps/vlc.png" },
     {"Videos", "totem ", "/usr/share/icons/hicolor/16x16/apps/totem.png" },
     {"Xnoise", "xnoise ", "/usr/share/icons/hicolor/32x32/apps/xnoise.png" },
 }

 local menuee69799670a33f75d45c57d1d1cd0ab3 = {
     {"Avahi Zeroconf Browser", "/usr/bin/avahi-discover", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Disk Usage Analyzer", "baobab", "/usr/share/icons/hicolor/16x16/apps/baobab.png" },
     {"Disk Utility", "mate-disk"},
     {"EtherApe", "etherape", "/usr/share/pixmaps/etherape.png" },
     {"File Manager PCManFM", "pcmanfm ", "/usr/share/icons/gnome/16x16/apps/system-file-manager.png" },
     {"GParted", "/usr/bin/gparted_polkit ", "/usr/share/icons/hicolor/16x16/apps/gparted.png" },
     {"Guake Terminal", "guake", "/usr/share/icons/hicolor/16x16/apps/guake.png" },
     {"Guymager", "gksudo guymager", "/usr/share/pixmaps/guymager_128.png" },
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"LSHW", "/usr/sbin/gtk-lshw", "///usr/share/lshw/artwork/logo.svg" },
     {"LXTerminal", "lxterminal", "/usr/share/icons/hicolor/128x128/apps/lxterminal.png" },
     {"Logs", "gnome-logs", "/usr/share/icons/hicolor/16x16/apps/gnome-logs.png" },
     {"MATE Terminal", "mate-terminal", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"MDB Tools", "gmdb2", "///usr/share/gmdb/glade/logo.xpm" },
     {"Manage Printing", "/usr/bin/xdg-open http://localhost:631/", "/usr/share/icons/hicolor/16x16/apps/cups.png" },
     {"Network Tools", "mate-nettool", "/usr/share/icons/hicolor/16x16/apps/mate-nettool.png" },
     {"Network Tools", "gnome-nettool", "/usr/share/icons/hicolor/16x16/apps/gnome-nettool.png" },
     {"Ophcrack", "ophcrack", "///usr/share/ophcrack/pixmaps/os.xpm" },
     {"Oracle VM VirtualBox", "VirtualBox ", "/usr/share/icons/hicolor/16x16/mimetypes/virtualbox.png" },
     {"System Log", "gnome-system-log", "/usr/share/icons/hicolor/16x16/apps/logview.png" },
     {"System Monitor", "gnome-system-monitor", "/usr/share/icons/gnome/16x16/apps/utilities-system-monitor.png" },
     {"Task Manager", "lxtask", "/usr/share/icons/gnome/16x16/apps/utilities-system-monitor.png" },
     {"Terminal", "gnome-terminal", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"Terminator", "terminator", "/usr/share/icons/hicolor/16x16/apps/terminator.png" },
     {"Tilda", "/usr/bin/tilda", "/usr/share/pixmaps/tilda.png" },
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Virtual Machine Manager", "virt-manager", "/usr/share/icons/hicolor/16x16/apps/virt-manager.png" },
     {"Wireshark", "wireshark ", "/usr/share/icons/hicolor/16x16/apps/wireshark.png" },
     {"XSSer", "/usr/bin/xsser --gtk --silent", "///usr/share/xsser/gtk/images/xssericon_24x24.png" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Xfce Terminal", "xfce4-terminal", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"dconf Editor", "dconf-editor", "/usr/share/icons/hicolor/16x16/apps/dconf-editor.png" },
 }

xdgmenu = {
    {"Accessibility", menue0e4fc6213e8b3593495a7260c3a4c2e},
    {"Accessories", menu98edb85b00d9527ad5acebe451b3fae6},
    {"Education", menude7a22a0c94aa64ba2449e520aa20c99},
    {"Games", menu251bd8143891238ecedc306508e29017},
    {"Graphics", menud334dfcea59127bedfcdbe0a3ee7f494},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Office", menudf814135652a5a308fea15bff37ea284},
    {"Other", menu6311ae17c1ee52b36e68aaf4ad066387},
    {"Programming", menue6f43c40ab1c07cd29e4e83e4ef6bf85},
    {"Sound & Video", menu52dd1c847264a75f400961bfb4d1c849},
    {"System Tools", menuee69799670a33f75d45c57d1d1cd0ab3},
}

